using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Platemates.Application.Dtos;
using Platemates.Application.Interfaces;

namespace Platemates.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class UsersController(IUserService userService) : ControllerBase
{
    private readonly IUserService _userService = userService;

    [HttpGet("me")]
    [Authorize]
    public async Task<ActionResult<UserResponseDto>> GetOrCreateCurrentUser(CancellationToken cancellationToken)
    {
        // DEBUG: Log all claims
        Console.WriteLine("=== ALL CLAIMS IN TOKEN ===");
        foreach (var claim in User.Claims)
        {
            Console.WriteLine($"{claim.Type}: {claim.Value}");
        }
        Console.WriteLine("===========================");

        // Get Clerk user ID from token (sub claim)
        var clerkUserId = User.FindFirst("sub")?.Value;

        if (string.IsNullOrWhiteSpace(clerkUserId))
        {
            return Unauthorized("Missing Clerk user id (sub) in token.");
        }

        // Get other claims from token
        var email =
            User.FindFirst("email")?.Value ??
            User.FindFirst("email_address")?.Value ??
            string.Empty;

        var username =
            User.FindFirst("username")?.Value
            ?? (email.Contains("@") ? email.Split('@')[0] : $"user-{clerkUserId[..6]}");

        // Use service to get or create user
        var userDto = await _userService.GetOrCreateUserAsync(
            Guid.Empty, // Will be generated by service
            clerkUserId,
            email,
            username,
            DateTime.UtcNow,
            null,
            null
        );

        return Ok(userDto);
    }
}
